routes/web.php
<?php

use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('welcome');
});

Auth::routes();
Route::middleware(['auth'])->group(function () {
	Route::get('/home', [App\Http\Controllers\HomeController::class, 'index'])->name('home');

	Route::resource('publicationhouses', App\Http\Controllers\PublicationhouseController::class);

	Route::resource('books', App\Http\Controllers\BookController::class);

	Route::resource('authors', App\Http\Controllers\AuthorController::class);
});

resources/views/publicationhouses/create.blade.php
@extends('layouts.app')

@section('content')
    <section class="content-header">
        <h1>
            Publicationhouse
        </h1>
    </section>
    <div class="content">
        @include('adminlte-templates::common.errors')
        <div class="box box-primary">
            <div class="box-body">
                <div class="row">
                    {!! Form::open(['route' => 'publicationhouses.store']) !!}

                        @include('publicationhouses.fields')

                    {!! Form::close() !!}
                </div>
            </div>
        </div>
    </div>
@endsection

resources/views/publicationhouses/edit.blade.php
@extends('layouts.app')

@section('content')
    <section class="content-header">
        <h1>
            Publicationhouse
        </h1>
   </section>
   <div class="content">
       @include('adminlte-templates::common.errors')
       <div class="box box-primary">
           <div class="box-body">
               <div class="row">
                   {!! Form::model($publicationhouse, ['route' => ['publicationhouses.update', $publicationhouse->id], 'method' => 'patch']) !!}

                        @include('publicationhouses.fields')

                   {!! Form::close() !!}
               </div>
           </div>
       </div>
   </div>
@endsection

resources/views/publicationhouses/fields.blade.php
<!-- Title Field -->
<div class="form-group col-sm-6">
    {!! Form::label('title', 'Title:') !!}
    {!! Form::text('title', null, ['class' => 'form-control','maxlength' => 255,'maxlength' => 255,'maxlength' => 255]) !!}
</div>

<!-- Established At Field -->
<div class="form-group col-sm-6">
    {!! Form::label('established_at', 'Established At:') !!}
    {!! Form::text('established_at', null, ['class' => 'form-control','id'=>'established_at']) !!}
</div>

@push('scripts')
    <script type="text/javascript">
        $('#established_at').datetimepicker({
            format: 'YYYY-MM-DD HH:mm:ss',
            useCurrent: true,
            sideBySide: true
        })
    </script>
@endpush

<!-- Owner Name Field -->
<div class="form-group col-sm-6">
    {!! Form::label('owner_name', 'Owner Name:') !!}
    {!! Form::text('owner_name', null, ['class' => 'form-control','maxlength' => 255,'maxlength' => 255,'maxlength' => 255]) !!}
</div>

<!-- Submit Field -->
<div class="form-group col-sm-12">
    {!! Form::submit('Save', ['class' => 'btn btn-primary']) !!}
    <a href="{{ route('publicationhouses.index') }}" class="btn btn-default">Cancel</a>
</div>

resources/views/publicationhouses/index.blade.php
@extends('layouts.app')

@section('content')
    <section class="content-header">
        <h1 class="pull-left">Publicationhouses</h1>
        <h1 class="pull-right">
           <a class="btn btn-primary pull-right" style="margin-top: -10px;margin-bottom: 5px" href="{{ route('publicationhouses.create') }}">Add New</a>
        </h1>
    </section>
    <div class="content">
        <div class="clearfix"></div>

        @include('flash::message')

        <div class="clearfix"></div>
        <div class="box box-primary">
            <div class="box-body">
                    @include('publicationhouses.table')
            </div>
        </div>
        <div class="text-center">
        
        </div>
    </div>
@endsection

resources/views/publicationhouses/show.blade.php
@extends('layouts.app')

@section('content')
    <section class="content-header">
        <h1>
            Publicationhouse
        </h1>
    </section>
    <div class="content">
        <div class="box box-primary">
            <div class="box-body">
                <div class="row" style="padding-left: 20px">
                    @include('publicationhouses.show_fields')
                    <a href="{{ route('publicationhouses.index') }}" class="btn btn-default">Back</a>
                </div>
            </div>
        </div>
    </div>
@endsection

resources/views/publicationhouses/show_fields.blade.php
<!-- Title Field -->
<div class="form-group">
    {!! Form::label('title', 'Title:') !!}
    <p>{{ $publicationhouse->title }}</p>
</div>

<!-- Established At Field -->
<div class="form-group">
    {!! Form::label('established_at', 'Established At:') !!}
    <p>{{ $publicationhouse->established_at }}</p>
</div>

<!-- Owner Name Field -->
<div class="form-group">
    {!! Form::label('owner_name', 'Owner Name:') !!}
    <p>{{ $publicationhouse->owner_name }}</p>
</div>

resources/views/publicationhouses/table.blade.php
<div class="table-responsive">
    <table class="table" id="publicationhouses-table">
        <thead>
            <tr>
                <th>Title</th>
        <th>Established At</th>
        <th>Owner Name</th>
                <th colspan="3">Action</th>
            </tr>
        </thead>
        <tbody>
        @foreach($publicationhouses as $publicationhouse)
            <tr>
                <td>{{ $publicationhouse->title }}</td>
            <td>{{ $publicationhouse->established_at }}</td>
            <td>{{ $publicationhouse->owner_name }}</td>
                <td>
                    {!! Form::open(['route' => ['publicationhouses.destroy', $publicationhouse->id], 'method' => 'delete']) !!}
                    <div class='btn-group'>
                        <a href="{{ route('publicationhouses.show', [$publicationhouse->id]) }}" class='btn btn-default btn-xs'><i class="glyphicon glyphicon-eye-open"></i></a>
                        <a href="{{ route('publicationhouses.edit', [$publicationhouse->id]) }}" class='btn btn-default btn-xs'><i class="glyphicon glyphicon-edit"></i></a>
                        {!! Form::button('<i class="glyphicon glyphicon-trash"></i>', ['type' => 'submit', 'class' => 'btn btn-danger btn-xs', 'onclick' => "return confirm('Are you sure?')"]) !!}
                    </div>
                    {!! Form::close() !!}
                </td>
            </tr>
        @endforeach
        </tbody>
    </table>
</div>